language: node_js

node_js:
  - "stable"
  - "4"
  - "0.12"

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm test
  - npm run test:backbone1.2
  - npm run benchmark
  - npm run test:saucelabs

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

after_success:
  - npm run coveralls
  - bash <(curl -s https://codecov.io/bash)
  - rm -rf coverage
