language: node_js

node_js:
  - "10"
  - "8"
  - "6"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - commitlint-travis
  - yarn lint
  - yarn test
  - yarn test:backbone1.2
  - if [[ $TRAVIS_NODE_VERSION = '8' ]] && [[ $TRAVIS_PULL_REQUEST = 'false' ]]; then SAUCELABS=true yarn test; fi
  - yarn benchmark
  - yarn build

after_success:
  - yarn test:coverage

notifications:
  email: false
