language: node_js

node_js:
  - 9
  - 8
  - 6

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn lint
  - yarn test
  - yarn test:backbone1.2
  - if [[ $TRAVIS_NODE_VERSION = '8' ]] && [[ $TRAVIS_PULL_REQUEST = 'false' ]]; then SAUCELABS=true yarn test; fi
  - yarn benchmark
  - yarn build

after_success:
  - yarn test:coverage

deploy:
  provider: npm
  email: ybiquitous@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    node: "8"

notifications:
  email: false
