language: node_js

node_js:
  - "8"
  - "7"
  - "6"

cache: yarn

script:
  - yarn lint
  - yarn test
  - yarn test:backbone1.2
  - SAUCELABS=true yarn test
  - yarn benchmark

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - rm -rf coverage

deploy:
  provider: npm
  email: ybiquitous@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true

after_deploy:
  - yarn github-release
