language: node_js

node_js:
  - "stable"
  - "4.2"
  - "0.12"

script:
  - "npm test"
  - "npm run lint"

before_script:
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

after_success:
  - "npm run coveralls"
  - "rm -rf coverage"
