language: node_js

node_js:
  # TODO: Test failed in Node.js v7.3
  # See https://github.com/karma-runner/karma/issues/2511
  - "7.2"
  - "6"
  - "4"

cache: yarn

script:
  - yarn lint
  - yarn test
  - yarn test:backbone1.2
  - SAUCELABS=true yarn test
  - yarn benchmark

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - rm -rf coverage

deploy:
  provider: npm
  email: 10koba01@gmail.com
  api_key:
    secure: UqjL0dvrDgtmzTUW0hLG1lI06cuI+WvUwpOiOFst1drIZahCZ8p7izgul1MMEPYqitBgYL5UcdKjATEziKSQBqKBFkhmhFj1iM0BJ8HV60axAFzmWvOyWVTcWdwr7XlOoFoTIVINRX5Q5Re4J3QKMMZBeArqzyG37iV8keqMtoiONjuoAeS89ax/hzKL1P49bKRYLpqlGWhrAqBEM2CxKuMZd7aqDZvJmsjTs94MTuUCwQ/NUzKBfdvBtHC0cKddyob0RRmUnGL5rhDinUOuhypw83s8y0VyRPJ1Txag8iKaqjHBa1uNsbMMdJyo8wZepRjeKmzYG405dn77emf8Oj7z+gxGHWlxmz0GNAl7lZVBNPbwmWaJv5j2BAM+BNu+tJdD2TogZDppC+0DUq6MPzaodk/57tLNMlj6Iu7YScQ/CoPVTm599IKySxrUuvgjZQ+sik6au3Wmvhd7XCXVBUw3uPWMq0om0gWPWhjilbijEiMWXaR4GhjDqs1cAoaNjF2Jj69NhQz34DS+l5I3Kcd2I4ZSC3ucVLyc95rCIoErK3ZYdwyHCshwGcv+R3MEki/x8yOznZki7LylTSX51WPLoS5ELvriljgB9okVSE3kYMEGT2gLQXTNUqMIuRtKCcFNsKD+iEnEZEkEUU8seqgc/l7lD2zjOB67YbRD910=
  on:
    tags: true

after_deploy:
  - yarn conventional-github-releaser
