language: node_js

node_js:
  - "7"
  - "6"
  - "4"

cache:
  directories:
    - $HOME/.yarn-cache

install:
  - npm install -g --cache-min=99999999 yarn
  - yarn

script:
  - yarn lint
  - yarn test
  - yarn test:backbone1.2
  - SAUCELABS=true yarn test
  - yarn benchmark

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - rm -rf coverage
