language: node_js

node_js:
  - "stable"
  - "4"

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm update
  - npm prune

script:
  - npm run lint
  - npm test
  - npm run test:backbone1.2
  - SAUCELABS=true npm test
  - npm run benchmark

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - rm -rf coverage
